name: CI - Conda

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  build-with-conda-and-test:
    name: "${{ matrix.os }} with SOFA master from Conda devel [QPSolver = ${{ matrix.qp_solver }}]"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest, ubuntu-24.04-arm]
        python_version: ["3.12"]
        build_type: ["Release"]
        qp_solver: ["qpOases", "proxQP"]

    steps:
    - name: Install miniconda [Linux & macOS & Windows]
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sofa
        auto-update-conda: true
        miniforge-version: latest
        python-version: ${{ matrix.python_version }}
        channels: conda-forge
        conda-remove-defaults: "true"

    - name: Install SOFA and SofaPython3 from devel packages
      shell: bash -l {0}
      run: |
        conda install sofa-devel sofa-python3 -c https://prefix.dev/sofa-framework-devel

    - name: Install compilation environment [Linux / macOS]
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      shell: bash -l {0}
      run: |
        conda install cmake cxx-compiler ninja pkg-config pybind11 cxxopts

    - name: Install compilation environment [Windows]
      if: contains(matrix.os, 'windows')
      shell: bash -l {0}
      run: |
        conda install cmake vs2022_win-64 ninja pkg-config pybind11 cxxopts

    - name: Checkout SOFA SoftRobots
      uses: actions/checkout@v4
      with:
        repository: SofaDefrost/SoftRobots
        ref: master
        path: SoftRobots

    - name: Configure, build & install SoftRobots
      shell: bash -l {0}
      run: |
        ls -al
        cd SoftRobots
        mkdir build
        cd build
        cmake .. -GNinja \
         -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
         -DPython_EXECUTABLE:PATH=${CONDA_PREFIX}/bin/python \
         -DSOFTROBOTS_BUILD_TESTS:BOOL=OFF
        cmake --build . --config ${{ matrix.build_type }} -v -j 2
        cmake --install . --config ${{ matrix.build_type }}

    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Install QP solver dependencies [proxQP]
      if: contains(matrix.qp_solver, 'proxQP')
      shell: bash -l {0}
      run: |
        conda install proxsuite
        echo "CMAKE_OPTS_QPSOLVER=-DSOFTROBOTSINVERSE_ENABLE_PROXQP=ON -DSOFTROBOTSINVERSE_ENABLE_QPOASES=OFF" >> "$GITHUB_ENV"

    - name: Install QP solver dependencies [qpOases]
      if: contains(matrix.qp_solver, 'qpOases')
      shell: bash -l {0}
      run: |
        conda install qpoases
        echo "CMAKE_OPTS_QPSOLVER=-DSOFTROBOTSINVERSE_ENABLE_PROXQP=OFF -DSOFTROBOTSINVERSE_ENABLE_QPOASES=ON" >> "$GITHUB_ENV"        

    - name: Print environment
      shell: bash -l {0}
      run: |
        conda info
        conda list
        env

    - name: Configure SoftRobots.Inverse
      shell: bash -l {0}
      run: |
        mkdir build
        cd build
        cmake .. -GNinja $CMAKE_OPTS_QPSOLVER \
         -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
         -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
         -DPython_EXECUTABLE:PATH=${CONDA_PREFIX}/bin/python \
         -DSOFTROBOTSINVERSE_BUILD_TESTS:BOOL=ON

    - name: Build SoftRobots.Inverse
      shell: bash -l {0}
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }} -v -j 2

    - name: Install SoftRobots.Inverse
      shell: bash -l {0}
      run: |
        cd build
        cmake --install . --config ${{ matrix.build_type }}

    - name: Test SoftRobots.Inverse
      shell: bash -l {0}
      run: |
        cd build
        ctest --output-on-failure -C ${{ matrix.build_type }}
